FROM alpine:3.15.0 as build

COPY ./source/ /usr/src/keydb 

WORKDIR /usr/src/keydb 

RUN set -eux; \
	\
	mkdir -p /usr/src; \
	mkdir -p /keydb_bin; \
	apk upgrade --no-cache --available; \
	apk add --no-cache --virtual .build-deps \
		gcc \
		linux-headers \
		make \
		musl-dev \
		openssl-dev \
		g++ \
		tcl-dev util-linux-dev libunwind-dev curl-dev \
	; \
	make -j "$(expr $(nproc) / 2)"; \
	cp ./src/keydb-* /keydb_bin

FROM alpine:3.15.0

ARG version
ENV REDIS_VERSION ${version}
ENV KEYDB_PRO_DIRECTORY=/usr/local/bin/

COPY --from=build /keydb_bin /usr/local/bin/
COPY docker-entrypoint.sh /usr/local/bin/

RUN set -eux; \
	\
	addgroup -S -g 1000 keydb && adduser -S -G keydb -u 999 keydb; \
	apk add --no-cache \
	tzdata bash 'su-exec>=0.2' \
	libuuid libcurl libunwind libgcc libstdc++; \
	mkdir /data && chown keydb:keydb /data && \
  	mkdir /flash && chown keydb:keydb /flash; \
	chmod +x /usr/local/bin/docker-entrypoint.sh; \
	cd /usr/local/bin && \
	mkdir -p /etc/keydb && \
	mv -f *.conf /etc/keydb && \
	# update config file for use in container
	sed -i 's/^\(bind .*\)$/# \1/' /etc/keydb/keydb.conf && \
	sed -i 's/^\(daemonize .*\)$/# \1/' /etc/keydb/keydb.conf && \
	sed -i 's/^\(dir .*\)$/# \1\ndir \/data/' /etc/keydb/keydb.conf && \
	sed -i 's/^\(logfile .*\)$/# \1/' /etc/keydb/keydb.conf && \
	sed -i 's/protected-mode yes/protected-mode no/g' /etc/keydb/keydb.conf; \
	rm -rf \
		/var/cache/apk/* \
		/tmp/* \
		/usr/share/man;

WORKDIR /data

ENTRYPOINT ["docker-entrypoint.sh"]

EXPOSE 6379
CMD ["keydb-server", "/etc/keydb/keydb.conf"]
